apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: nginx-root
spec:
  image: harbor.mbentley.net/mbentley/nginx-hostname@sha256:3bca3799c4cc304cecf578aeb8650cddb68973685dffc44a758a09c96bad401b
  replicas: 1
  ports:
  - name: main
    port: 8080
